pipeline:
  identifier: Build_harness_go_pipeline_sample_1692296251773
  name: Build harness-go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1692296168499
        repoName: ixxbit/harness-go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Enter Welcome Message
                  identifier: Enter_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo 'Welcome Harn World'
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
